//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindTheGap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gap
    {
        public int GapID { get; set; }
        public string gapSummary { get; set; }
        public System.DateTime gapStartTime { get; set; }
        public System.DateTime gapEndTime { get; set; }
    }
}
